services:
  api_produtor:
    container_name: api_produtor
    image: api_produtor:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80
    environment:
      #- DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/postgres
       - DATABASE_URL=postgresql://postgres:HBoTrLWGPkNMgpuVnkTSYcuUlRGKxgIZ@autorack.proxy.rlwy.net:55199/railway      
  
    depends_on:
     - db
  
  db:
    image: postgres:16.1
    container_name: database
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HBoTrLWGPkNMgpuVnkTSYcuUlRGKxgIZ
      POSTGRES_DB: railway
    ports:
      - 55199
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: