services:
  api_produtor:
    container_name: api_produtor
    image: api_produtor:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/postgres
  #     #  DB_USER: postgres
  #     #  DB_PWD:  alan2009
  #     #-  DB_HOST: localhost
  #     #-  DB_PORT: 5432
    depends_on:
     - db
  
  db:
    image: postgres:16.1
    container_name: database
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: